Setup initial repo configuration with Cypress
juan-carvajal/cypress-workshop pull request #1
Opened 2020-07-24 14:45 UTC by juan-carvajal

2020-07-24 14:55 UTC, holgiosalos requested changes
Creo que subiste todos los ejemplos de cypress, no es necesario agregarlos. 

Borra por favor los siguientes directorios:
- cypress/fixtures
- cypress/integration
- cypress/plugins
- cypress/screenshots
- cypress/support

2020-07-24 14:55 UTC, holgiosalos commented on .github/CODEOWNERS
> +* @aperdomob @germandavid85 @luigisamurai @yesidbalvin @Scot3004 @santirogu
Los code owners deberiamos ser: 
@leonleo997
@holgiosalos
@renardete
@valeryibarra

2020-07-24 14:55 UTC, holgiosalos commented on .vscode/settings.json
> +}
EOF

2020-07-24 14:55 UTC, holgiosalos commented on cypress/fixtures/profile.json
> +}
EOF

2020-07-24 14:55 UTC, holgiosalos commented on cypress/fixtures/users.json
> +]
EOF

2020-07-24 15:05 UTC, juan-carvajal commented
> Creo que subiste todos los ejemplos de cypress, no es necesario agregarlos.
> 
> Borra por favor los siguientes directorios:
> 
> * cypress/fixtures
> * cypress/integration
> * cypress/plugins
> * cypress/screenshots
> * cypress/support

Cypress busca las especificaciones de las pruebas dentro del folder integration, creo que ese debe de ir. Tambien, support, plugins y videos se crean al correr las pruebas, toca incluirlos en el ignore?

2020-07-24 15:09 UTC, holgiosalos commented
> > Creo que subiste todos los ejemplos de cypress, no es necesario agregarlos.
> > Borra por favor los siguientes directorios:
> > 
> > * cypress/fixtures
> > * cypress/integration
> > * cypress/plugins
> > * cypress/screenshots
> > * cypress/support
> 
> Cypress busca las especificaciones de las pruebas dentro del folder integration, creo que ese debe de ir. Tambien, support, plugins y videos se crean al correr las pruebas, toca incluirlos en el ignore?

Entiendo, preguntemosle a @renardete y @leonleo997 que estan mas acostumbrados a la configuracion de cypress, si no se pueden borrar, entonces lo mejor seria agregarlos al .gitignore, a menos que Yesid o Juanfe conozcan una mejor forma de configurar cypress.

2020-07-24 17:39 UTC, yesid-lopez reviewed
> > > Creo que subiste todos los ejemplos de cypress, no es necesario agregarlos.
> > > Borra por favor los siguientes directorios:
> > > 
> > > * cypress/fixtures
> > > * cypress/integration
> > > * cypress/plugins
> > > * cypress/screenshots
> > > * cypress/support
> > 
> > 
> > Cypress busca las especificaciones de las pruebas dentro del folder integration, creo que ese debe de ir. Tambien, support, plugins y videos se crean al correr las pruebas, toca incluirlos en el ignore?
> 
> Entiendo, preguntemosle a @renardete y @leonleo997 que estan mas acostumbrados a la configuracion de cypress, si no se pueden borrar, entonces lo mejor seria agregarlos al .gitignore, a menos que Yesid o Juanfe conozcan una mejor forma de configurar cypress.

Está bien, no hay problema con que subas esos archivos que subiste, lo que sí debes hacer es borrar el folder de examples de integration, y veo que lo hiciste

2020-07-24 17:39 UTC, leonleo997 commented on .gitignore
> +# End of https://www.toptal.com/developers/gitignore/api/visualstudiocode,node,windows
please add a section to ignore the useless cypress files

2020-07-24 17:39 UTC, leonleo997 commented on package.json
> +    "cypress": "^4.11.0"
add cypress as a dev dependency

2020-07-24 17:40 UTC, leonleo997 commented
can you add a screenshot of the test passing successfully?

2020-07-24 17:41 UTC, leonleo997 commented
@holgiosalos please remove your change request

2020-07-24 17:51 UTC, holgiosalos approved these changes

2020-07-27 16:57 UTC, juan-carvajal commented
![image](https://user-images.githubusercontent.com/39658930/88569550-35d5c180-d000-11ea-96b1-455bbdad3e55.png)
@leonleo997 @holgiosalos

2020-07-27 17:09 UTC, juan-carvajal commented
cypress/videos and cypress/screenshots were added to .gitignore, also cypress was installed as a dev dependency.
I found some directions as to how to scructure files in cypress, it suggests to ignore these two folders.
https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests.html#Folder-Structure

2020-07-27 17:10 UTC, merged